server:
  port: 8090
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.github.novicezk.midjourney: debug
knife4j:
  enable: true
  openapi:
    title: Midjourney Proxy API文档
    description: 代理 MidJourney 的discord频道，实现api形式调用AI绘图
    concat: novicezk
    url: https://github.com/novicezk/midjourney-proxy
    version: v2.5.1
    terms-of-service-url: https://github.com/novicezk/midjourney-proxy
    group:
      api:
        group-name: API
        api-rule: package
        api-rule-resources:
          - com.github.novicezk.midjourney.controller

mj:
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  ng-discord:
    cdn: https://draw.iti8.fun
  accounts:
    - guild-id: 1152509414838915102
      channel-id: 1152509942423633931
      user-token: MTE1MjQ4NTg2OTM2NjgwODYxOQ.Gjy1Fv.1xNxUc6mfpXxkdNVrty34tw1BAT6HwDwDij7JM
      user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.289 Safari/537.36