mj:
  task-store:
    type: in_memory
    timeout: 30d

  proxy:
    port: 10809
    host: 127.0.0.1

  translate-way: null
  accounts:
    - guild-id: 1152509414838915102
      channel-id: 1152509942423633931
      user-token: MTE1MjQ4NTg2OTM2NjgwODYxOQ.GQ52dq.NzdDl5FfGYTYlm0XMqeys_wMw3QWNgSWQcSgVs
      user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.289 Safari/537.36

